export const columns = [
  {
    name: 'questionQuestion',
    label: '問題',
    align: 'left',
    field: 'questionQuestion',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'questionCreaterId',
    align: 'left',
    label: '發問者學號',
    field: 'questionCreaterId',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'questionAddtime',
    align: 'left',
    label: '發問時間',
    field: 'questionAddtime',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];

export const columns_1 = [
  {
    name: 'dataUrl',
    label: '來源',
    align: 'left',
    field: 'dataUrl',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'dataFilename',
    align: 'left',
    label: '資源名稱',
    field: 'dataFilename',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'dataFiletype',
    align: 'left',
    label: '資源種類',
    field: 'dataFiletype',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];

export const columns_2 = [
  {
    name: 'questionQuestion',
    label: '問題',
    align: 'left',
    field: 'questionQuestion',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'questionCreaterId',
    align: 'left',
    label: '發問者學號',
    field: 'questionCreaterId',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'questionAddtime',
    align: 'left',
    label: '發問時間',
    field: 'questionAddtime',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'trans',
    align: 'left',
    label: '轉移次數',
    field: 'trans',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];

export const rowsData = [
  {
    questionId: 1,
    questionQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    questionCreaterId: '121',
    qaLastUpdaterId: null,
    questionAddtime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: 'http://www.im.fju.edu.tw/site/?...',
    sourceName: '高中生問答集',
    sourceType: 'url',
  },
  {
    questionId: 2,
    questionQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    questionCreaterId: '121',
    qaLastUpdaterId: null,
    questionAddtime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: 'http://www.im.fju.edu.tw/site/?...',
    sourceName: '高中生問答集',
    sourceType: 'url',
  },
  {
    questionId: 3,
    questionQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    questionCreaterId: '121',
    qaLastUpdaterId: null,
    questionAddtime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: '問題.pdf',
    sourceName: '資管系問答集',
    sourceType: 'pdf',
  },
];

export const rowsData_1 = [
  {
    questionId: 1,
    questionQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    questionCreaterId: '121',
    qaLastUpdaterId: null,
    questionAddtime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    trans: 3,
  },
];
