export const columns = [
  {
    name: 'qaQuestion',
    label: '問題',
    align: 'left',
    field: 'qaQuestion',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'qaCreateId',
    align: 'left',
    label: '發問者學號',
    field: 'qaCreateId',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'qaAsktime',
    align: 'left',
    label: '發問時間',
    field: 'qaAsktime',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];

export const columns_1 = [
  {
    name: 'source',
    label: '來源',
    align: 'left',
    field: 'source',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'sourceName',
    align: 'left',
    label: '資源名稱',
    field: 'sourceName',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'sourceType',
    align: 'left',
    label: '資源種類',
    field: 'sourceType',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];

export const columns_2 = [
  {
    name: 'qaQuestion',
    label: '問題',
    align: 'left',
    field: 'qaQuestion',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'qaCreateId',
    align: 'left',
    label: '發問者學號',
    field: 'qaCreateId',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'qaAsktime',
    align: 'left',
    label: '發問時間',
    field: 'qaAsktime',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'trans',
    align: 'left',
    label: '轉移次數',
    field: 'trans',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];

export const columns_3 = [
  {
    name: 'acID',
    label: '教職員編號',
    align: 'left',
    field: 'acID',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'acName',
    label: '名稱',
    align: 'left',
    field: 'acName',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },

  {
    name: 'acEMAIL',
    align: 'left',
    label: 'EMAIL',
    field: 'acEmail',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'acApply',
    align: 'left',
    label: '申請時間',
    field: 'acApply',
    format: (val: Date) => `${val.toLocaleString()}`,
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  {
    name: 'permission',
    align: 'left',
    label: '狀態',
    field: 'permission',
    sortable: true,
    headerStyle: 'font-size: medium;font-weight: 900',
  },
  { name: 'actions', align: 'right', label: '', field: '' },
];
export const rowsData = [
  {
    qaId: 1,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: 'http://www.im.fju.edu.tw/site/?...',
    sourceName: '高中生問答集',
    sourceType: 'url',
  },
  {
    qaId: 2,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: 'http://www.im.fju.edu.tw/site/?...',
    sourceName: '高中生問答集',
    sourceType: 'url',
  },
  {
    qaId: 3,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: '問題.pdf',
    sourceName: '資管系問答集',
    sourceType: 'pdf',
  },
  {
    qaId: 4,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    source: '問題.pdf',
    sourceName: '資管系問答集',
    sourceType: 'pdf',
  },
];

export const rowsData_1 = [
  {
    qaId: 1,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    trans: 3,
  },
  {
    qaId: 2,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    trans: 3,
  },
  {
    qaId: 3,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    trans: 3,
  },
  {
    qaId: 4,
    qaQuestion: 'Frozen Yogurt',
    qaAnswer: 'answer',
    qaCreateId: '121',
    qaLastUpdaterId: null,
    qaAsktime: new Date(),
    qaUpdatetime: null,
    qaDaletetime: null,
    qaStatus: 'pending',
    trans: 3,
  },
];
//權限的
export const rowsData_2 = [
  {
    acID: '123456789',
    acName: '小明',
    acEmail: 'a12345678@gmail.com',
    acApply: new Date(),
    permission: '未確認',
  },
  {
    acID: '222222222',
    acName: '大明',
    acEmail: 'b1234123@gmail.com',
    acApply: new Date(),
    permission: '未確認',
  },
];
